### ISSUE TITLE
The stream or file "/var/www/storage/logs/laravel.log" could not be opened in append mode: Failed to open stream: Permission denied

### ISSUE THREAD

**Issue by devmansurov** [refactorian/laravel-docker#84]
When I run all these commands:

```
git clone https://github.com/refactorian/laravel-docker.git
cd laravel-docker
docker compose up -d --build
docker compose exec php bash
composer setup

```
And open the application itself in the browser I get this error:

> The stream or file "/var/www/storage/logs/laravel.log" could not be opened in append mode: Failed to open stream: Permission denied

[Link to shared error](https://flareapp.io/share/VmeNxbAP)

When I added the storage folder to the php service then I received this error:

```
    php:
        build: .docker/php
        ports:
            - 5173:5173
        volumes:
            - .:/var/www:cached
            - .:/var/www/storage
```

Then get this error:

> There is no existing directory at "/var/www/storage/logs" and it could not be created: Permission denied
